# Generated by Django 6.0.7 on 2026-07-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('routing_key', models.CharField(max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'db_table': 'logs',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
